spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8077/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable service discovery
          lowerCaseServiceId: true
      routes:
        - id: loan-application-service-route-1
          uri: lb://LOAN-APPLICATION-SERVICE  # Load balance to the "accounts" service registered with Eureka
          predicates:
            - Path=/api/v1/corporate-clients/**
            # Route requests with /accounts/** path to the "accounts" service
        - id: loan-application-service-route-2
          uri: lb://LOAN-APPLICATION-SERVICE  # Load balance to the "accounts" service registered with Eureka
          predicates:
            - Path=/api/v1/loan-applications/**
            # Route requests with /accounts/** path to the "account
        - id: loan-application-service-route-3
          uri: lb://LOAN-APPLICATION-SERVICE  # Load balance to the "accounts" service registered with Eureka
          predicates:
            - Path=/api/v1/loan-officers/**
            # Route requests with /accounts/** path to the "account
        - id: loan-application-service-route-4
          uri: lb://LOAN-APPLICATION-SERVICE  # Load balance to the "accounts" service registered with Eureka
          predicates:
            - Path=/api/v1/loan-reviews/**
            # Route requests with /accounts/** path to the "account
#        - id: securityservice-route
#          uri: lb://SECURITYSERVICE  # Load balance to the "security" service registered with Eureka
#          predicates:
#            - Path=/api/auth/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true


info:
  app:
    name: api-gateway
    description: "Self Service Gateway Server Application"
    version: "1.0.0"


server:
  port: 8090

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"
